#!/usr/bin/bash

declare -ra std_deps=$(jq -r ".deps[] | .[0]" package.json)
declare -ra ext_deps=("github:micropytest/micropython-stdlib/src/typing" "github:micropytest/should")

for dep in ${std_deps[@]}; do
  micropython -m mip install $dep
done

for dep in ${ext_deps[@]}; do
  micropython -m mip install $dep
done