#!/usr/bin/bash

declare -ra prod=($(jq -r ".deps[] | .[0]" package.json))
declare -ra dev=("github:micropytest/should" "unittest" "unittest-discover")

for dep in "${prod[@]}" "${dev[@]}"; do
  micropython -m mip install -t lib "$dep"
done
